apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeljob-registry
    version: v1alpha1
  name: model-registry
  namespace: kube-system
spec:
  ports:
  - name: http-8080
    nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: modeljob-registry
    version: v1alpha1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: modeljob-registry
      version: v1alpha1
      control-plane: model-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: modeljob-registry
        version: v1alpha1
        control-plane: model-registry
    spec:
      containers:
      - command:
        - /model-registry
        args:
        - --enable-leader-election
        image: harbor.caicloud.com/release/model-registry:4066990-dirty
        name: model-registry
        env:
        - name: ORMB_DOMAIN
          value: "harbor.caicloud.com"
        - name: ORMB_USERNAME
          valueFrom:
            secretKeyRef:
              name: ormb
              key: ormbUsername
        - name: ORMB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ormb
              key: ormbPassword
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10