apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: model-registry-controller
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry-controller
  namespace: system
  labels:
    control-plane: model-registry-controller
spec:
  selector:
    matchLabels:
      control-plane: model-registry-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: model-registry-controller
    spec:
      containers:
      - command:
        - /model-registry-controller
        args:
        - --enable-leader-election
        image: controller:latest
        name: model-registry-controller
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
