apiVersion: kleveross.io/v1alpha1
kind: ModelJob
metadata:
  name: modeljob-mxnet-convert
  namespace: default
spec:
  # Add fields here
  model: "harbor.caicloud.com/release/mxnet:v1"
  desiredTag: "harbor.caicloud.com/release/onnx_convert:v2"
  conversion:
    mmdnn:
      from: "MXNETParams"
      to: "ONNX"
