apiVersion: kleveross.io/v1alpha1
kind: ModelJob
metadata:
  name: modeljob-h5-convert
  namespace: default
spec:
  # Add fields here
  model: "harbor.caicloud.com/release/h5:v1"
  desiredTag: "harbor.caicloud.com/release/savemodel_convert:v2"
  conversion:
    mmdnn:
      from: "H5"
      to: "SavedModel"

