# permissions for end users to view modeljobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modeljob-viewer-role
rules:
- apiGroups:
  - modeljobs.caicloud.io
  resources:
  - modeljobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - modeljobs.caicloud.io
  resources:
  - modeljobs/status
  verbs:
  - get
