apiVersion: v1
data:
  caffemodel-convert: '{{ .Values.docker.registry }}/{{ .Values.conversion.caffemodel-convert }}'
  mxnetparams-convert: '{{ .Values.docker.registry }}/{{ .Values.conversion.mxnetparams-convert }}'
  h5-convert: '{{ .Values.docker.registry }}/{{ .Values.conversion.h5-convert }}'
  caffemodel-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.caffemodel-extract }}'
  netdef-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.netdef-extract }}'
  graphdef-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.graphdef-extract }}'
  h5-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.h5-extract }}'
  mxnetparams-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.mxnetparams-extract }}'
  onnx-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.onnx-extract }}'
  savedmodel-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.savedmodel-extract }}'
  torchscript-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.torchscript-extract }}'
  pmml-extract: '{{ .Values.docker.registry }}/{{ .Values.extraction.pmml-extract }}'
  ormb-storage-initializer: "{{ .Values.docker.registry }}/{{ .Values.model.ormb-storage-initializer  }}"
kind: ConfigMap
metadata:
  name: modeljob-image-config
  namespace: {{ .Values.namespace }}