apiVersion: v1
kind: Secret
metadata:
  name: ormb
type: Opaque
data:
  # base64 formatted username `admin`
  ormbUsername: YWRtaW4=
  # base64 formatted password `ORMBtest12345`
  ormbPassword: T1JNQnRlc3QxMjM0NQ==