apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "klever-modeljob-operator.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "klever-modeljob-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "klever-modeljob-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "klever-modeljob-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "klever-modeljob-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ORMB_DOMAIN
              value: {{ .Values.ormbDomain }}
            - name: ORMB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ormb
                  key: ormbUsername
            - name: ORMB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ormb
                  key: ormbPassword
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
